site_name: "Rank Torrent Name"
site_description: "Rank Torrent Name is a powerful Python library that revolutionizes the way you handle filenames."
site_author: 'Dreu LaVelle'
site_url: 'https://ranktorrentname.com'

repo_name: 'RTN'
repo_url: 'https://github.com/dreulavelle/rank-torrent-name'

nav:
  - Home: index.md
  - Users: 
    - Getting Started: Users/FAQ.md
    - Languages: Users/Languages.md
  - Developers: 
    - Introduction: Developers/Introduction.md
    - Parsing: Developers/Parsing.md
    - Settings Model: Developers/Settings.md
    - Ranking Model: Developers/Ranking.md
    - Models: Developers/Models.md
    - Sorting: Developers/Sorting Torrents.md
    - Extras: Developers/Extras.md
  - Modules: 
    - Parser: Developers/Modules/parser.md
    - Ranker: Developers/Modules/ranker.md
    - Fetch: Developers/Modules/fetch.md
    - Models: Developers/Modules/models.md
    - Exceptions: Developers/Modules/exceptions.md
    - Patterns: Developers/Modules/patterns.md
    - Extras: Developers/Modules/extras.md
  - Contributing: contributing.md
  - License: license.md

plugins:
  - search  
  - mkdocstrings:
      handlers:
        python:
          paths: [RTN]
          # options:
          #   heading_slug_func: 'slugify'

theme:
  name: 'material'
  custom_dir: overrides
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.instant
      - navigation.instant.progress
      - navigation.sections
      - navigation.indexes
      - navigation.top
      - navigation.pruning
      - navigation.path
      - search.suggest
      - search.share
      - content.code.annotate
      - content.code.copy
      - announce.dismiss
  icon:
    logo: logo

  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Follow system preferences

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-5
        name: Set fire to my eyes!

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-4
        name: Darken the world!
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  social:
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/rivenmedia' 
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/dreulavelle/rank-torrent-name'

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - codehilite:
      linenums: false
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
